# Generated by Django 4.1.7 on 2023-02-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_image_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
