# Generated by Django 4.1.7 on 2023-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('comment', models.TextField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
